/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_hibernate_boot_archive_scan_spi_ClassFileArchiveEntryHandler */

#ifndef _Included_org_hibernate_boot_archive_scan_spi_ClassFileArchiveEntryHandler
#define _Included_org_hibernate_boot_archive_scan_spi_ClassFileArchiveEntryHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_hibernate_boot_archive_scan_spi_ClassFileArchiveEntryHandler
 * Method:    decrypt
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_hibernate_boot_archive_scan_spi_ClassFileArchiveEntryHandler_decrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
